replicaCount: 1
image:
  repository: duylinh158/nestjs-rent-cars
  pullPolicy: IfNotPresent
  tag: v1.24-dev
service:
  protocol: TCP
  type: NodePort
  port: 3000
  targetPort: 3000
env:
  secret:
    DB_HOST: db-rent-cars.cf4auqe43vet.us-east-1.rds.amazonaws.com
    DB_PORT: '3306'
    DB_USER: admin
    DB_PASSWORD: Onepiece
    DB_NAME: rent_cars
    AUTH_SECRET: secret123
