apiVersion: v1
kind: Service
metadata:
  labels:
    app: rent-cars
  name: rent-cars
spec:
  ports:
    - name: 'http'
      port: {{ .Values.service.port }}
      protocol: {{ .Values.service.protocol }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: rent-cars
  type: {{ .Values.service.type }}
